hashicorp/envconsul

cli.go
Depends on hashicorp/consul#581
=> Switch to github.com/hashicorp/consul/api

README.md, cli.go, config.go, config_test.go
=> Add -max-stale

.travis.yml, Makefile, README.md, cli.go, cli_test.go, config.go, config_test.go, flags.go
- Adds support for basic HTTP auth
- Adds support for SSL
- Adds support for logging to syslog
- Adds support for specifying retry intervals
- Improves test coverage
=> Add new APIs from Consul Template

cli.go, cli_test.go
=> Detect CLI usage errors

Makefile, README.md, cli.go, cli_test.go, config.go, config_test.go, runner.go, runner_test.go, scripts/build.sh, signals_windows.go
=> Add preliminary support for Vault

README.md, cli.go, cli_test.go, config.go, config_test.go, runner.go
=> Add splay option

runner.go
In some cases, we return nil for the exitCh. This happens when there is no data from Consul or when an error occurs. In those cases, we were overwriting the parent's exitCh, effectively orphaning the channel. In this, the subprocess would exit, but its exit was never propagated to the parent.
Fixes GH-85
/cc @slackpad 
Also, I have no idea how to write a test for this.
=> Do not overwrite exitCh if it is nil

runner.go, runner_test.go
=> Overwrite existing envvars

runner.go
=> Check is returned value is nil

.circleci/config.yml
Testing out CircleCI vs. Travis for CI. CircleCI is not seeing the branch, so maybe it needs to be a pull request.
=> initial circleci config

Makefile, docker/alpine/Dockerfile, docker/scratch/Dockerfile
Various updates to the Makefile and Docker builds.
=> Build updates

README.md
=> Update Vault Example

CHANGELOG.md
I'll update the date when doing the actual release.
=> changelog notes for 0.9.2

.circleci/config.yml, docker/alpine/Dockerfile, docker/pristine/Dockerfile, docker/scratch/Dockerfile
This is to prevent rate limiting of docker pulls.
=> switch to hashicorp docker mirror

docker/alpine/Dockerfile, docker/alpine/docker-entrypoint.sh
Closes #230
@eikenb I am wondering if `/envconsul/data` folder is being used at all.
It looks like it was copy-pasted from `consul-template`.
Please, let me know if I should remove it from the [Dockerfile](https://github.com/hashicorp/envconsul/blob/master/docker/alpine/Dockerfile#L70)
=> run entrypoint in alpine Docker image as unprivileged user

docker/alpine/Dockerfile, docker/alpine/docker-entrypoint.sh
=> fix: remove obsolete docker-base package

.github/workflows/ci.yml
Adds a basic CI testing workflow using Github Actions.
Getting the basics in place for the new standard.
=> add github action based CI

README.md, config_prefix.go, runner.go, runner_test.go
Closes #235 and adds feature of applying a per-key formatting
=> feature: allow getting only a subset of keys from Vault secret

cli.go
=> improve once help output

cli.go
It was outputting to STDERR which complicated scripting and such as that
is not standard behavior.
=> fix version and help output to go to STDOUT

.gitignore
Relates to https://github.com/hashicorp/envconsul/pull/281#discussion_r911455346
=> Add config.hcl and .vscode to .gitignore

go.mod
=> update go version to 1.22.4

CHANGELOG.md
As a part of release process, the changelog is updated with relevant items.
Note: The version is already up to the date
=> Updating CHANGELOG and version for the release v0.13.3

README.md
Replace `master` with `main` in README.
Minor update for consistency and clarity.
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.
=> Update default branch reference in README.md

.release/security-scan.hcl, CHANGELOG.md
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.
=> Prepare 0.13.4

.release/security-scan.hcl, CHANGELOG.md
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.
=> update changelog and suppress cves
