cli.go, runner_test.go
This updates cli to use new watcher API as of https://github.com/hashicorp/consul-template/commit/2cbf5d1524f9620d94accd08fa2e4f6a6e96cdd6
Also fix a race in `runner_test` which randomly fails on my machine.
=> Update to use new watcher API as of commit 2cbf5d1524

README.md, cli.go, cli_test.go, config.go, config_test.go, flags.go, runner.go, runner_test.go, signals.go, signals_windows.go
- Adds support for multiple prefixes
- Propagates select signals to child processes
This adds the `-prefix` multi-flag as discussed in #27.
- Fixes #27 
- Fixes #31
=> Support multiple prefixes and propagate signals

cli.go, cli_test.go, config.go, config_test.go, runner.go, signals.go, signals_windows.go
I made a quick attempt to fix #45 
Would like some feedback on the approach as far as code consistency and quality. I currently have the same issue as @alexmic with needing to send a `SIGHUP` to gunicorn to reload properly, otherwise things start to fail pretty hard. I have a custom build with the default signal changed to `SIGHUP` for now as a workaround.
The ability to set the signal with this pull request would work by setting `killsig` through the CLI or via a config file and will default to the current default, `SIGTERM`.
Setting it would be `envconsul -killsig SIGHUP` for CLI and `killsig = "SIGHUP"` for the config file.
=> Kill signal configurable

README.md
As @aantono pointed out the `README` was not updated for the newly added `-killsig` config option. I thought some feedback was going to be given on the original pull request #48 before cleaning things up and having it merged in. @sethvargo let me know if this explains things clear enough for the `README`.
=> Update readme for killsig option

cli.go
The -ssl command-line flag is skipped because the ssl section was missing.
=> fixing ignored -ssl flag

config.go
since the log config hasn't loaded yet, this will print regardless of the log level
=> removing noisy debug line

cli.go, cli_test.go, config.go, runner.go, runner_test.go
Added a "pristine" option such that the environment generated does not inherit from the existing shell environment.  The only values that are put into the environment are those from the consul service.
=> Added "pristine" option 

runner.go
When using the -pristine option, a call is being made to make() and returned to cmdEnv. This isn't needed for a string type (cmdEnv is declared as a string on line 264). The call to make() creates a slice padded with whitespace equal to the length of r.env. When cmdEnv is later appended to with the actual key/values from consul, these key/values are added to the end of this slice, leaving the padded whitespace in place which leads to multiple empty lines equal to r.env. The call to make() is needed when -pristine is not being used because of the subsequent call to copy().
=> Fix for extra newlines noted in issue #59

README.md
It appears from the code and the examples that the ssl-ca-cert and ssl-cert options are supported by the runtime. Adding them into the documentation so that it is clear.
=> Update README.md to include ssl-ca-cert and ssl-cert

README.md
According to #94 and https://www.hashicorp.com/blog/hashicorp-and-fastly.html, the correct place to download binary releases is https://releases.hashicorp.com/envconsul/ and not https://github.com/hashicorp/envconsul/releases.
=> point users to the new releases page @ releases.hashicorp.com

config.go
This fixes an issue with Vault tokens not being renewed automatically
unless they are hardcoded in configuration. This commit makes it
possible for tokens set via `VAULT_TOKEN` in the environment to also be
renewed automatically when `renew` is configured.
Resolves https://github.com/hashicorp/envconsul/issues/99 and related to https://github.com/hashicorp/consul-template/commit/2431448c7edd50fd2a2165f4a709f0bb1736e0a3
=> Load VAULT_TOKEN from the environment into config

README.md, config.go, config_test.go, runner.go
If I have a single vault with secrets for many staging/development environments I would have to alter my application to prefix its settings with the environment name.
This change allows user to use the same deployment script for each of those environments, save changing the secret's path.
``` javascript
secret {
path = 'application_name/staging-01'
}
```
``` python
MY_SETTING = os.environ['APPLICATION_NAME_%s_MY_SETTING' % os.environ.get('ENVIRONMENT', '')]
```
becomes
``` javascript
secret {
no_prefix = true
path = 'application_name/staging-01'
}
```
``` python
MY_SETTING = os.environ['MY_SETTING']
```
=> Add the ability to opt out of path prefixing for secrets

runner.go
Using the default *rand* source produces a deterministic sequence of values each time `envconsul` is run. This causes issues when running multiple docker instances, for example, because `rand.Int63n(nanoseconds)` returns the same value.
=> make splay more random

config.go, config_test.go
This is useful when needing to interpolate environment variables into a config when using configuration options that can't be passed on the command line:
```sh
envconsul -config <(<<EOF
secret {
path = "$MY_SECRET_PATH"
no_prefix = true
}
EOF
) -once -pristine env
```
=> Allow reading config from named pipe

runner.go
consulenv should not send SIGKILL silently. 
I was contemplating making this a warning so it shows up by default, but this level seems to be intended for things that consulenv itself doesn't expect. Let me know if you disagree and I will happily change it to a warning.
=> Add log message for forceful child terminations

cli.go
Fix a typo and use consistent wording in the usage message.
=> Fix typo and wording in usage

runner.go
We needed a way to start envconsul with no output and couldn't find a way to squelch the 'looking at vault...' output.
This pull request moves that output to the INFO log level output.
=> Added "looking at vault" to INFO log level

README.md
Currently we state that the EnvConsul CLI interface supports all options in the config file, which is not the case when I tested the binary.
Corrected the README.md to reflect this as to not confuse users
=> ReadMe Corrections

runner.go
Fixes: #194
Previously, when the `-pid-file` config option was set, the PID file was never stored.
=> Store PID when PID file is specified

runner.go, runner_test.go
Fixes: #166 
With this PR the runner will no longer panic if the type of a secret value isn't a string, it will just skip it.
=> Don't panic if secret value isn't string

runner.go, runner_test.go
Fixes: #155
The contents of the Exec.Env block of the config was not being processed when the runner was started.
This PR adds the expected functionality based on the config file [documentation](https://github.com/hashicorp/envconsul/blob/master/README.md#configuration-file).
The logic is a modified version of consul-template's [EnvConfig.Env()](https://github.com/hashicorp/consul-template/blob/master/config/env.go#L106).
The reason for reimplementing it in `envconsul` is that the config data needs to be merged into the env variables received from Consul and Vault.
Flow as proposed:
- If `-pristine` CLI flag or base `pristine` cfg field is set to `false`, load env variables from `os`
- Add env variables from Consul and Vault
- If `exec.env.pristine` in cfg is `true`, clear existing env …
=> Respect exec.env config block

config_prefix.go, runner.go, runner_test.go
Fixes: #190
Previously, the configuration option `no_prefix` was implemented for keys read from Vault but not from Consul.
This PR implements the behavior as stated in the [docs](https://github.com/hashicorp/envconsul/blob/master/README.md): 
> This [noprefix] tells Envconsul to not prefix the keys with their parent "folder".
=> Respect no_prefix for Consul keys

runner.go
Shell variables were interpolated and backtick blocks evaluated during
the exec/command parsing. It was interpolating the variables using the
original calling process' environment settings without any of the
consul, vault, custom, etc. values injected into it. The backtick blocks
are also executed in the calling processes' environment in the same way.
Neither of these make sense given the execution model of envconsul. Also
the supporting library doesn't really do that great of a job of
mimicking shell semantics. Best path seemed to just remove both.
Fixes #180
=> Disable shell interpolation and backtick eval

README.md, cli.go, cli_test.go
Allows speficying no-prefix globally for all prefixes/secrets from the
command line. Argument handling must be done after standard parsing as
it relies on -prefix and -secret already being set.
Fixes #198
=> add -no-prefix cli argument

runner.go, runner_test.go
The previous pull request from @catsby supported the Vault KV2 store. However, it assumed that the Vault secret only had a single key. Because Vault stores every secret as a JSON object, a secret can have multiple keys. For instance, a KV2 secret can be:
{
"data": {
"db_username": "john",
"db_password": "smith"
},
"metadata": .....
}
In the previous code, it would just read the "db_username" key and then stop. It should be reading every field inside "data".
I updated the test to include this scenario and also added comments in the code to show the KV1 versus the KV2 JSON structure.
=> Added support for Vault KV2 store with multiple key/value secrets

CHANGELOG.md, runner.go
Internal bug filing. They suggested only including it in TRACE logs but IMO it was improper to log secrets ever and so am removing it.
=> don't log values/secrets pulled from vault

Makefile, docker/pristine/Dockerfile
Build all arm binaries with CGO enabled to address golang bug..
https://github.com/golang/go/issues/32912
Includes arm64 to standardize the platforms supported with those
consul-template supports.
Fixes #227
=> use CGO with arm build (fixes go bug)

runner.go
Use the client API to get the token instead of accessing directly off
data structure. This ensures you always get the real token both in the
normal case and when working with a wrapped token.
Fixes #222
=> renew using unwrapped token

README.md, cli.go, config_prefix.go, config_test.go
Issue came up when user had a secret config section with no path set (but had noprefix) and where setting the path on the cli. The documentation on how this was handled was unclear so the user thought it was a bug.
I fixed the issue so that their test would have worked by filtering out the secret config entry with no path (as the path is required).
I also updated the documentation to help clarify how prefix and secret (they use the same code) work.
Fixes #165
=> fix issue with secret/prefix entries with no path

README.md, cli.go
Including the mention in the README about how it isn't used. I think
that is confusing as it is never mentioned anywhere else in the docs.
Fixes #237
=> remove -exec-reload-signal from docs

README.md, config_test.go, runner.go
This PR adds the ability to use Go templates in prefix paths, and use environment variables in these templates.
For the application our team works on, we have the same binary which can start up in different roles, eg. "background-worker" or "api-server". We have a mix of global (per-environment) config, and some role specific config, all of which is currently in Consul.
We'd love to be able to use `envconsul` without needing to render a separate config file per role using configuration management, and instead being able to provide a template to build the Consul/Vault key prefix. We'd also like to make use of the "shadowing" ability by using multiple `prefix` stanzas in the configuration, allowing us to retain the ability to set custom key formatters which is unavailable in the CLI.
We can …
=> Allow users to use ENV vars in prefix paths using Go templates

README.md, config_test.go, go.sum, runner.go, runner_test.go
Updates envconsul to use inclusive language while keeping backward compatibility for the changed configuration option names. Configuration documentation, inline documentation, and variable names are updated to have minimal occurrences of the renamed values.
* `exec.env.blacklist` is renamed to `exec.env.denylist`
* `exec.env.whitelist` is renamed to `exec.env.allowlist`
We encourage practitioners to update their configuration to match these changes, but existing configurations are still backward compatibile.
Resolves #243
=> Change whitelist/blacklist to allowlist/denylist

README.md, cli.go, config_test.go, runner.go
Consul-template already supports this, so it is just a matter of adding
the command line parameter, passing the token on through to the watcher,
documenting and testing.
This was an enhancement request that came in from a client (so no github
issue to close).
=> add support for vault agent token files

docker/alpine/Dockerfile
This adopts the new HashiCorp PGP key, as described at https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512/2 and https://hashicorp.com/security.
Please merge after reviewing 🙏
=> Adopt new pgp key

runner.go
Consul-template grew a configurable default lease time for vault but
it did it in a way that made envconsul use a 0 lease time.
This fixes that by setting the default lease time to the new default as
specified in vault's config (in consul-template).
Fixes #272
=> set consul-tempalte's vault default lease

cli.go
Scheduler uses SIGURG to pre-emtp and can't filter them itself as there
is no way to discern scheduler signals from others. Skip logging them to
keep them out of logs as they are confusing (they show up as 'urgent I/O
condition').
Fixes #285
=> skip logging Go's runtime scheduler signals

cli.go
consult-template is still using the standard log package
These tweaks limits it to logging just the message and handing that to hclog. It makes it look mostly like it is an normal log entry. Only diff is that it uses different notation for subsections.
Might be useful just to keep as it makes using the standard log package work easily with hclog.
Plus some tweaks to deal with error level indicated by either ERR or ERROR.
=> have standard 'log' package output to hclog + ERROR level tweaks

runner.go
A default value was changed to be configurable by changing the fixed
const into a module level variable that was set at runtime. When updated
to the new consul-template version this setting of the new variable was
missed. This adds it.
Fixed #310 
Note there are no tests as this section of code has none currently and it will all get reworked as part of the hashicat update anyways, so no use it adding a bunch of testing at this point.
=> add missing call to set module level variable

.github/workflows/build.yml, Dockerfile
We have missing LICENSE file in the compiled artifacts, this PR adds this.
DoD
=> add license file to linux distribution and docker image
